# Generated by Django 6.0.7 on 2026-08-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('calcada_buraco', 'Calçada danificada / buraco'), ('fiacao_exposta', 'Fiação exposta'), ('lixo_irregular', 'Lixo irregular'), ('bueiro_alagamento', 'Bueiro entupido / alagamento'), ('falta_iluminacao', 'Falta iluminação'), ('outros', 'Outros')], max_length=50)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(help_text='Ex: Rua, Número, Bairro', max_length=155)),
                ('imagem', models.ImageField(blank=True, upload_to='ocorrencias/%Y/%m')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('reportado', 'Reportado'), ('em_analise', 'Em análise'), ('resolvido', 'Resolvido')], default='reportado', max_length=20)),
            ],
        ),
    ]
