# Generated by Django 6.0.7 on 2026-08-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='ocorrencias/%Y/%m/'),
        ),
    ]
