# Generated by Django 6.0.7 on 2026-08-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_alter_ocorrencia_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'ordering': ['-data_criacao']},
        ),
    ]
